lesson_12
Perkir/Rails_qna pull request #10
Opened 2016-12-21 21:46 UTC by Perkir

2016-12-22 12:43 UTC, palkan requested changes

2016-12-22 12:43 UTC, palkan commented on app/models/user.rb
> +  def new_user
Вот такой один большой комментарий: https://gist.github.com/palkan/8ddcc7b3b507250f3a2bda0a7fbb80f2

2016-12-22 19:26 UTC, Perkir commented on app/models/user.rb
> +  def new_user
А я подумал, что хороший способ=)

2016-12-23 09:37 UTC, palkan requested changes
Что-то я не пойму, ты просто решил отказаться от этого функционала?) Где обработка случая, когда нам не возвращают email?

2016-12-24 00:58 UTC, Perkir commented
Подумал что работает, но после того как удалил юзера из бд - разобрался =)

2016-12-25 20:17 UTC, palkan commented on app/models/user.rb
> +      user = User.new(password: password, email: '', password_confirmation: password)
А зачем нам вообще в этом случае инициировать объект `User`? Просто возвращай `nil`.

2016-12-25 20:24 UTC, Perkir commented on app/models/user.rb
> +      user = User.new(password: password, email: '', password_confirmation: password)
Так событие запроса email сработает только если email пустой

2016-12-25 20:24 UTC, merged