lesson_10
Perkir/Rails_qna pull request #8
Opened 2016-12-09 20:28 UTC by Perkir

2016-12-16 10:02 UTC, palkan requested changes
Пожалуйста, делай отступы везде одинаково: где-то у тебя один пробел (и это жутко нечитабельно), где-то - два.
Лучше везде два.

2016-12-16 10:02 UTC, palkan commented on app/assets/javascripts/answers.coffee
> +  #.bind 'ajax:error', (e, xhr, status, error) ->
?

2016-12-16 10:02 UTC, palkan commented on app/assets/javascripts/questions.coffee
> +     $('.voting .question-errors').empty() #не хочет обнулять
Нужно дебажить, сходу не видно, в чём тут дело.

Попробуй просто в консоли браузера ввести `$('.voting .question-errors')`, что выведет? Ну и `$('.voting .question-errors').empty()`.

А значение рейтинга обновляет? Или он вообще не попадает в эту часть условия.

2016-12-16 11:50 UTC, PersiOnOff commented on app/assets/javascripts/questions.coffee
> +     $('.voting .question-errors').empty() #не хочет обнулять
рейтинг обновляет

2016-12-16 12:33 UTC, palkan commented on app/channels/answers_channel.rb
> +  def follow_answer(params)
Вот здесь ошибка: ты назвал аргумент `params`, тем самым как бы _переопределив_ метод `params`, который есть в канале и содержит данные, преданные при подключении.

В этом методе ты не получаешь аргументы, ты вызываешь его просто как `@perform 'follow_answer'`.

В итоге у тебя некорректная подписка.

В общем, просто убери аргумент из метода, тогда `params` будет возвращать верный объект, с id.

2016-12-18 09:39 UTC, palkan requested changes

2016-12-18 09:39 UTC, palkan commented on app/controllers/comments_controller.rb
> +    ActionCable.server.broadcast("question_comments_#{@question_id}", data)
И что такое `@question_id`? Поэтому и не работает.

2016-12-19 07:57 UTC, merged